export const actionTypes = (() => {
  return {
    FETCH_POKEMON_DATA: 'FETCH_POKEMON_DATA',
    POKEMON_DATA_FETCH_SUCCESS: 'POKEMON_DATA_FETCH_SUCCESS',
    POKEMON_DATA_FETCH_FAILURE: 'POKEMON_DATA_FETCH_FAILURE'
  };
})();